# Generated by Django 2.2.5 on 2019-10-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('question', models.TextField(blank=True, default='', verbose_name='вопрос')),
                ('answer', models.TextField(blank=True, default='', verbose_name='ответ')),
            ],
            options={
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'verbose_name': 'Часто задаваемый вопрос',
            },
        ),
    ]
