# Generated by Django 2.2.5 on 2019-10-24 08:58

from django.db import migrations


def seed_faq(apps, schema_editor):
    FAQ = apps.get_model('core', 'FAQ')
    questions = list()

    questions.append(FAQ(
        question='В каком формате добавлять адреса для рассылки?',
        answer='Адреса для рассылки можно указать вручную на странице создания рассылки, или загрузить списком в '
               'формате TXT-файла. Файл должен содержать список валидных email, разделённых переносом строки.',
    ))

    questions.append(FAQ(
        question='Что такое ссылка для отписки от рассылки?',
        answer='Это ссылка, которую вы можете добавить в ваш HTML-шаблон, чтобы клиент рассылки мог отписаться от '
               'рассылки по данному email-аккаунту. Ссылка уникальна для вашего email-аккаунта. По факту отписки '
               'в базе данных фиксируется текущий email, закрепленный за email-аккаунтом. Таким образом, клиент '
               'рассылки не получит письмо, даже если будет создан новый аккаунт со старым email.'
    ))

    questions.append(FAQ(
        question='Как работает ссылка для отписки от рассылки?',
        answer='Ссылку необходимо вставить в HTML-шаблон рассылки, чтобы клиент рассылки мог перейти по ней и '
               'указать в форме отписки свой email, а также причину (опционально). Список отписавшихся от каждого '
               'аккаунта и причины отписок можно посмотреть на странице "Отписавшиеся".'
    ))

    questions.append(FAQ(
        question='Что означают ошибки отправки?',
        answer='При отправке email SMTP-сервер может не выполнить команду по ряду причин: не удалось установить '
               'соединение или оно было оборвано, указанный почтовый адрес не существует, email был расценён как спам, '
               'и т.д. Мы рекомендуем тщательно изучать статистику отправки и причины сбоев после каждой рассылки '
               'для предотвращения ошибок.'
    ))

    questions.append(FAQ(
        question='Есть ли ограничения на отправку писем?',
        answer='При отправке писем через общедоступные SMTP-сервисы (Яндекс, Mail.ru, Google) действуют правила '
               'сервисов (<a href="https://yandex.ru/support/mail/web/letter/create/send-many-letters.html">Яндекс</a>,'
               ' <a href="https://group-mail.com/sending-email/email-send-limits-and-options/">Google</a>, '
               '<a href="https://www.epochta.ru/help/mailer/09_smtp.htm">Mail.ru</a>). Если вы используете персональный'
               ' SMTP-сервер, то никаких ограничений, кроме собственных ограничений вашего сервера, не действует. '
               'Персональные SMTP-серверы можно настроить по своему усмотрению.'
    ))

    questions.append(FAQ(
        question='Могут ли мои письма попасть в спам?',
        answer='Да, письма могут попасть в спам. Чтобы этого не произошло, необходимо придерживаться рекомендаций.'
    ))

    questions.append(FAQ(
        question='Как проверить, что мой email не попал в спам-фильтры?',
        answer='Проверить email, с которого вы отправляете, можно при помощи '
               '<a href="https://dnsbl.smtp.bz/">спам-баз</a>.'
    ))

    FAQ.objects.bulk_create(questions)


def delete_faq(apps, schema_editor):
    FAQ = apps.get_model('core', 'FAQ')
    FAQ.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_faq_model'),
    ]

    operations = [
        migrations.RunPython(seed_faq, delete_faq),
    ]
