# Generated by Django 2.2.5 on 2019-11-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_external_keys'),
        ('core', '0002_seed_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('question', models.TextField(blank=True, default='', verbose_name='вопрос')),
                ('answer', models.TextField(blank=True, default='', verbose_name='ответ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'Вопрос клиента',
                'verbose_name_plural': 'Вопросы клиентов',
            },
        ),
    ]
