# Generated by Django 2.2.5 on 2020-02-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_external_keys'),
        ('core', '0003_client_questions_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='email')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='имя')),
                ('feedback_text', models.TextField(blank=True, default='', verbose_name='текст обращения')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
