# Generated by Django 2.2.5 on 2019-09-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_profile_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSMTPServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='название')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='сервер')),
                ('port', models.IntegerField(default=0, verbose_name='порт')),
            ],
            options={
                'verbose_name_plural': 'Общие SMTP-серверы',
                'verbose_name': 'Общий SMTP-сервер',
            },
        ),
        migrations.CreateModel(
            name='CustomSMTPServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('host', models.CharField(blank=True, default='', max_length=255, verbose_name='сервер')),
                ('port', models.IntegerField(default=0, verbose_name='порт')),
            ],
            options={
                'verbose_name_plural': 'Пользовательские SMTP-серверы',
                'verbose_name': 'Пользовательский SMTP-сервер',
            },
        ),
        migrations.CreateModel(
            name='CustomSMTPServerToProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='название')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile', verbose_name='профиль')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smtp.CustomSMTPServer', verbose_name='сервер')),
            ],
            options={
                'unique_together': {('server', 'profile')},
                'verbose_name': 'Связь SMTP-пользователь',
                'verbose_name_plural': 'Связи SMTP-пользователь',
            },
        ),
    ]
