# Generated by Django 2.2.5 on 2019-09-26 11:41

from django.db import migrations


def seed_smtp(apps, schema_editor):
    CommonSMTPServer = apps.get_model('smtp', 'CommonSMTPServer')
    mail_smtp = CommonSMTPServer.objects.create(name='Mail.ru', host="smtp.mail.ru", port=2525)
    yandex_smtp = CommonSMTPServer.objects.create(name='Yandex.ru', host="smtp.yandex.ru", port=587)


def delete_smtp(apps, schema_editor):
    CommonSMTPServer = apps.get_model('smtp', 'CommonSMTPServer')
    CommonSMTPServer.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0001_smtp_models'),
    ]

    operations = [
        migrations.RunPython(seed_smtp, delete_smtp),
    ]
