# Generated by Django 2.2.5 on 2019-09-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0002_seed_smtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsmtpserver',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='название'),
        ),
        migrations.DeleteModel(
            name='CustomSMTPServerToProfile',
        ),
    ]
