# Generated by Django 2.2.5 on 2019-09-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smtp', '0003_fix_models'),
        ('accounts', '0001_profile_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='Email')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='Пароль')),
                ('common_smtp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smtp.CommonSMTPServer', verbose_name='общий smtp')),
                ('custom_smtp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smtp.CustomSMTPServer', verbose_name='пользовательский smtp')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_accounts', to='accounts.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Email-аккаунт',
                'verbose_name_plural': 'Email-аккаунты',
            },
        ),
    ]
