# Generated by Django 2.2.5 on 2019-10-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_email_account_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('template', models.TextField(blank=True, default='', verbose_name='html-шаблон')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='html_templates', to='accounts.Profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'HTML-шаблон',
                'verbose_name_plural': 'HTML-шаблоны',
            },
        ),
    ]
