# Generated by Django 2.2.5 on 2019-10-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_html_template_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmltemplate',
            name='name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Название'),
        ),
    ]
