# Generated by Django 2.2.5 on 2019-10-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_account_model'),
        ('mailings', '0002_name_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddresseeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='публикация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='Название')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addressee_lists', to='accounts.Profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name_plural': 'Списки адресатов',
                'verbose_name': 'Список адресатов',
            },
        ),
        migrations.CreateModel(
            name='Addressee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('addressee_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addressees', to='mailings.AddresseeList', verbose_name='список адресатов')),
            ],
            options={
                'verbose_name_plural': 'Адресаты',
                'verbose_name': 'Адресат',
                'unique_together': {('email', 'addressee_list')},
            },
        ),
    ]
