# Generated by Django 2.2.5 on 2019-10-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_external_keys'),
        ('mailings', '0003_addressee_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.EmailAccount', verbose_name='email-аккаунт')),
                ('html_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailings.HTMLTemplate', verbose_name='HTML-шаблон')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'История рассылки',
                'verbose_name_plural': 'История рассылки',
            },
        ),
    ]
