# Generated by Django 2.2.5 on 2019-10-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_unsubscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscriber',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='причина отписки'),
        ),
    ]
