# Generated by Django 2.2.5 on 2019-11-14 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0008_subject_fromname_to_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltemplate',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='html_templates', to='accounts.Profile', verbose_name='профиль'),
        ),
    ]
